### ISSUE TITLE
[PoC] TorchDisc: accelerating PyTorch training via LTC + BladeDISC

### ISSUE THREAD

**Issue by Yancey1989** [alibaba/BladeDISC#156]
## Background

BladeDISC is an end-to-end compiler that supports dynamic shape features, and dynamic shape is widely used on the training scene, this issue descript how to improve PyTorch training performance with DISC based on the LazyTensorCore(LTC) mechanism.

feature branch: https://github.com/alibaba/BladeDISC/tree/features/torch_disc_devel

## Design Overview
![image](https://user-images.githubusercontent.com/1426912/157614718-e9fcde04-a61b-401b-b35d-13704bb7edce.png)

1. According to LTC, a MARK API should be called manually at the end of each iteration to sync and execute a Graph on a physical device.
2. Lowering To TorchScript, LTC uses TorchScript as the backend engine, ref [TSBackendImpl](https://github.com/pytorch/pytorch/blob/lazy_tensor_staging/lazy_tensor_core/lazy_tensor_core/csrc/ts_backend/backend_impl.cpp#L34), we can use it lower Lazy IR to TorchScript IR.
3. Cluster DISC SubGraph, 
4. DISC Compilation Stage
  a. mhlo conversation,  DISC uses MLIR::mhloas the front-end, we should convert TorchScript IR to mhlo before compilation.
  b. compiling to an executable program, call DISC entry function to compile mhlo IR to an executable file (a dynamic library file).  
  c. disc execution, call DISC RAL to execute the executable program with input Tensors.
5. TorchScript Execution, finally call torch::jit::GraphExecutorto execute the TorchScript IR and return the result Tensors.

## Implement and TODO Actions

To implement the above features, we should build a Pybind library `_torch_disc.so` to expose step_mark API with some important C++ functions, the TODO actions as the following:

- [x] setup a building environment to build `_torch_disc.so` with Torch LTC, Mhlo Builder, and DISC. #158 
- [x] cluster DISC nodes into sub-graph (maybe implement cluster algorithms with a fake function). #173 
- [x] compilation DISC sub-graph and register the DISC engine #188 
- [x] demonstration TorchDISC with MNIST training. #207 #230 

## Reference
1. PyTorch LazyTensor branch: https://github.com/pytorch/pytorch/tree/lazy_tensor_staging/lazy_tensor_core
2. PyTorch/XLA backend example: https://github.com/pytorch/xla/tree/asuhan/xla_ltc_plugin

**Comment by fortianyou** [comment]
> library _torch_disc.so to expose step_mark API

What difference between our `disc.step_mark()` and PyTorch LTC's 'lazy_tensor_core.step_mark()`. I think eventually we can reuse the API from PyTorch LTC?

**Comment by fortianyou** [comment]
Perhaps we could add mnist and bert as the driven case in our tasks?

**Comment by Yancey1989** [comment]
> What difference between our disc.step_mark() and PyTorch LTC's lazy_tensor_core.step_mark(). I think eventually we can reuse the API from PyTorch LTC?

Not exactly the same,  `disc.step_mark()` should include the additional MHLO conversion and clustering stage.

> Perhaps we could add mnist and bert as the driven cases into our tasks?

That's a great idea, will add a task in the TODO actions.

**Comment by Yancey1989** [comment]
I will close this PR, all the PoC tasks have been done and we merged the feature branch to master, will keep tracing this feature with [project](https://github.com/alibaba/BladeDISC/projects/1) .
