### ISSUE TITLE
passing all disc op unit tests with torch-mlir converter

### ISSUE THREAD

**Issue by Yancey1989** [alibaba/BladeDISC#371]
This issue lists all disc op unit tests that torch-mlir converter needed

- [x] test_unary_ops.py @fortianyou 
- [x] test_activation.py @Yancey1989  #382 
- [ ] test_batchnorm.py
- [x] test_binary_ops.py @fortianyou 
- [ ] test_blacklist.py
- [ ] test_block_ops.py
- [x] test_broadcast.py @fortianyou 
- [ ] test_const.py #445 
- [ ] test_conv_ops.py @qiuxiafei 
- [ ] test_disc_engine.py
- [ ] test_list.py
- [x] test_matmul.py @fortianyou 
- [ ] test_multi_streams.py
- [ ] test_nn_ops.py
- [x] test_reduction.py @fortianyou 
- [x] test_shapes.py @fortianyou 
- [ ] test_tensor.py
- [ ] test_is_mlir_mhlo_supported.py
- [x] Also, we will add conversion passes unit tests based on FileCheck, https://github.com/alibaba/BladeDISC/issues/366

@Yancey1989 @wyzero @qiuxiafei

_Originally posted by @fortianyou in https://github.com/alibaba/BladeDISC/issues/369#issuecomment-1149547304_
