### ISSUE TITLE
Add op conversions that are needed in Bert Training

### ISSUE THREAD

**Issue by tanyokwok** [alibaba/BladeDISC#441]
The dump toolkit dumps the transformer training graph based on LTC, next we should implement following op converters:

- [ ] aten::_log_softmax
- [ ] aten::_log_softmax_backward_data
- [ ] aten::_softmax
- [ ] aten::_softmax_backward_data
- [x] aten::add
- [ ] aten::addcdiv
- [ ] aten::addcmul
- [ ] aten::clamp
- [ ] aten::embedding
- [ ] aten::embedding_dense_backward
- [ ] aten::gelu_backward @Yancey1989 #520 
- [x] aten::mm
- [x] aten::mul
- [ ] aten::native_dropout @Yancey1989 #520 
- [ ] aten::native_dropout_backward @fortianyou https://github.com/pai-disc/torch-mlir/pull/15
- [ ] aten::native_layer_norm @fortianyou  #479
- [ ] aten::native_layer_norm_backward @fortianyou https://github.com/pai-disc/torch-mlir/pull/15
- [ ] aten::nll_loss_backward
- [ ] aten::nll_loss_forward 
- [ ] aten::norm
- [x] aten::permute have been implemented in #424 
- [ ] aten::reciprocal 
- [x] aten::reshape have been implemented in #429 
- [x] aten::slice have been implemented in #430 
- [ ] aten::sqrt
- [ ] aten::stack
- [x] aten::sum have been implemented in #410 
- [ ] aten::tanh_backward
- [ ] aten::zeros_like
~- [ ] aten::_to_copy~
~- [ ] aten::clone~
~- [ ] aten::copy_~

**Comment by fortianyou** [comment]
- [ ] aten::_log_softmax
- [ ] aten::_log_softmax_backward_data
- [ ] aten::_softmax
- [ ] aten::_softmax_backward_data
- [ ] aten::_to_copy
- [ ] aten::add
- [ ] aten::addcdiv
- [ ] aten::addcmul
- [ ] aten::clamp
- [ ] aten::clone
- [ ] aten::copy_
- [ ] aten::embedding
- [ ] aten::embedding_dense_backward
- [ ] aten::gelu_backward
- [ ] aten::mm
- [ ] aten::mul
- [ ] aten::native_dropout
- [ ] aten::native_dropout_backward
- [ ] aten::native_layer_norm
- [ ] aten::native_layer_norm_backward
- [ ] aten::nll_loss_backward
- [ ] aten::nll_loss_forward
- [ ] aten::norm
- [ ] aten::permute
- [ ] aten::reciprocal
- [ ] aten::reshape
- [ ] aten::slice
- [ ] aten::sqrt
- [ ] aten::stack
- [ ] aten::sum
- [ ] aten::tanh_backward
- [ ] aten::zeros_like
